### ISSUE TITLE
关于新版Chrome的Cookie文件被占用问题

### ISSUE THREAD

**Issue by kuA35sSaasd** [sujiawei00/naturahi#3]
https://github.com/moonD4rk/HackBrowserData/issues/233

你好，能根据这个“卷影技术”实现不关闭Chrome抓取cookie么，因为关闭chrome真的动静太大了。。。。

**Comment by Naturehi666** [comment]
给我一下版本号 ，我去尝试写一下

**Comment by kuA35sSaasd** [comment]
> 给我一下版本号 ，我去尝试写一下

Chrome版本 116.0.5845.111（正式版本） （64 位）
115其实已经出现了问题了。。。。

HackBrowserData为[v0.4.4](https://github.com/moonD4rk/HackBrowserData/releases/tag/v0.4.4)

我尝试编译dev和master的源码发现还是Cookie被占用问题。。。。
![image](https://github.com/Naturehi666/searchall/assets/104559292/cdf7fc06-d93f-4509-a42c-c14423ff6123)
![image](https://github.com/Naturehi666/searchall/assets/104559292/242abea7-927d-4536-b9e9-8eab905c31c4)

**Comment by Naturehi666** [comment]
好的 我尝试修复


www.1050631369
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Naturehi666/searchall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月24日(星期四) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Naturehi666/searchall] 关于新版Chrome的Cookie文件被占用问题 (Issue #3)





  
给我一下版本号 ，我去尝试写一下
  
Chrome版本 116.0.5845.111（正式版本） （64 位）
 115其实已经出现了问题了。。。。
 
HackBrowserData为v0.4.4

**Comment by kuA35sSaasd** [comment]
> 好的 我尝试修复 [www.1050631369](http://www.1050631369) ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Naturehi666/searchall" ***@***.***&gt;; 发送时间:&nbsp;2023年8月24日(星期四) 上午10:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Naturehi666/searchall] 关于新版Chrome的Cookie文件被占用问题 (Issue #3) 给我一下版本号 ，我去尝试写一下 Chrome版本 116.0.5845.111（正式版本） （64 位） 115其实已经出现了问题了。。。。 HackBrowserData为v0.4.4 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

非常感谢

**Comment by doge-dog** [comment]
https://github.com/kmahyyg/go-rawcopy

**Comment by doge-dog** [comment]
已经找到替换卷影的方式，可直接写入代码中，https://github.com/kmahyyg/go-rawcopy

**Comment by Naturehi666** [comment]
666

**Comment by Naturehi666** [comment]
已完成需求

**Comment by doge-dog** [comment]
> 已完成需求

666

**Comment by Fomovet** [comment]
> 已完成

蹲一个更新

**Comment by Naturehi666** [comment]
你还要啥更新！
